version: '2'

services:

  # Let's Encrypt nginx-proxy. Resources:
  #   https://github.com/indiehosters/nginx
  #   https://github.com/gilyes/docker-nginx-letsencrypt-sample     # explains below
  nginx-proxy:
    image: nginx:alpine
    container_name: nginx-proxy
    restart: unless-stopped
    volumes:
      - ./proxy/conf.d:/etc/nginx/conf.d
      - ./proxy/vhost.d:/etc/nginx/vhost.d
      - ./proxy/html:/usr/share/nginx/html
      - ./proxy/certs:/etc/nginx/certs:ro
      - ./proxy/proxy.conf:/etc/nginx/proxy.conf:ro
    ports:
      - "80:80"
      - "443:443"
    networks:
      front:
        ipv4_address: 172.25.0.2
  nginx-gen:
    image: jwilder/docker-gen
    container_name: nginx-gen
    command: "-notify-sighup nginx-proxy -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf"
    restart: unless-stopped
    depends_on: [nginx-proxy]
    volumes_from: [nginx-proxy]
    volumes:
      - ./proxy/templates/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      front:
        ipv4_address: 172.25.0.3
  nginx-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx-letsencrypt
    restart: unless-stopped
    links:
      - nginx-proxy
      - nginx-gen
    volumes_from: [nginx-proxy]
    volumes:
      - ./proxy/certs:/etc/nginx/certs
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - NGINX_DOCKER_GEN_CONTAINER=nginx-gen
    networks:
      front:
        ipv4_address: 172.25.0.4

  # Nginx server
  website:
    image: nginx:alpine
    container_name: website
    restart: unless-stopped
    links:
      - nginx-proxy
    environment:
      - VIRTUAL_HOST=huseyinkozan.com.tr
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=huseyinkozan.com.tr
      - LETSENCRYPT_EMAIL=posta@huseyinkozan.com.tr
      - LETSENCRYPT_TEST            # from .env file
    volumes:
      - ./public:/usr/share/nginx/html:ro
    networks:
      front:
        ipv4_address: 172.25.0.10


# Static IP : http://stackoverflow.com/q/37242217/3620661
networks:
  front:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.25.0.0/16
          gateway: 172.25.0.1
